name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 14
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt update
        sudo apt install ffmpeg
    - name: run backend node server
      run: cd node && npm i && node main.js &
    - name: Waiting for server
      run: |
        while ! curl -s "http://localhost:1088/" | sh -c "jq .status | grep ready"; do
          echo -n '.'
          sleep 1
        done
        echo "Done wait for server"
    - name: run script
      run: python shanbei.py
    - name: count words
      run: find ./download/ -name '*.mp3'  |   wc -l | xargs -I{} echo "There are {} words in all"
    - name: generate ffmpeg input for concat
      run: python generate_name.py
    - name: concat files
      run: ffmpeg -f concat -safe 0 -i filenamelist.txt -ab 192k output.mp3
    - name: Upload result for job 
      uses: actions/upload-artifact@v1
      with:
        name: download
        path: ./download
    - name: Upload concated file for job 
      uses: actions/upload-artifact@v1
      with:
        name: output.mp3
        path: ./output.mp3

