name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt install ffmpeg
    - name: run script
      run: |
        python shanbei.py
    - name: generate ffmpeg input for concat
      run: python generate_name.py
    - name: concat files
      run: ffmpeg -f concat -safe 0 -i filenamelist.txt -ab 192k output.mp3
    - name: Upload result for job 
      uses: actions/upload-artifact@v1
      with:
        name: download
        path: ./download
    - name: Upload concated file for job 
      uses: actions/upload-artifact@v1
      with:
        name: output.mp3
        path: ./output.mp3

